version: '3'
services:
  authentication:
    build: scazares/mintik-authentication-service:latest
    depends_on:
      - mongodb
    environment:
      APP_PORT: 3000
      DB_NAME: authentication-db
      API_SECRET: mysecret
    env_file:
      - .env
    networks:
      - app-network

  mailer:
    build: scazares/mintik-mailer-service:latest
    depends_on:
      - mongodb
      - authentication
    environment:
      APP_PORT: 3005
      APP_DIR: ${CONTAINER_APP_PATH}
      DB_NAME: mailer-db
      JOB_POLL_INTERVAL_MS: 5000
      JOB_WAIT_MS: 1000
      SENDER_HOST: smtp.gmail.com
      SENDER_PORT: 587
      SENDER_SECURE: false
      SENDER_SERVICE: gmail
      SENDER_ADDRESS: scazares.dev@gmail.com
      SENDER_PASS: vxpn wpxg ffqy kvao
    env_file:
      - .env
    networks:
      - app-network

  mech-sync:
    build: scazares/mintik-mech-sync-service:latest
    volumes:
      - ${SERVER_MECH_PATH}:${CONTAINER_MECH_PATH} 
    depends_on:
      - mongodb
      - authentication
      - mailer
    environment:
      APP_PORT: 3010
      DB_NAME: mech-sync-db
      APP_DIR: ${CONTAINER_APP_PATH}
      MECH_DIR: ${CONTAINER_MECH_PATH}    
      JOB_POLL_INTERVAL_MS: 5000
      JOB_WAIT_MS: 1000
    env_file:
      - .env
    mem_limit: "8g"
    mem_reservation: "1g"
    networks:
      - app-network    

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ${SERVER_DB_PATH}:/data/db
    env_file:
      - .env
    networks:
      - app-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - //./pipe/docker_engine:/tmp/docker.sock:ro
    depends_on:
      - mongodb
      - authentication
      - mailer
      - mech-sync
    networks:
      - app-network

networks:
  app-network:
